# Use the official Python image as a base
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the Poetry configuration files
COPY pyproject.toml poetry.lock /app/

# Install Poetry
RUN pip install poetry

# Install dependencies
RUN poetry install --no-dev --no-interaction --no-ansi

# Copy the application code
COPY app /app/app

# Expose the port Flask runs on
EXPOSE 5000

# Set the environment variable for Flask
ENV FLASK_APP=app
ENV FLASK_RUN_HOST=0.0.0.0

# Start the Flask application
CMD ["poetry", "run", "flask", "run"]
